"use client";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import React, { useReducer } from "react";
import { appReducer } from "@/reducer/appReducer";
import { init } from "@/common/init";
import { Provider } from "@/context/appContext";

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(appReducer, init);
  return (
    <html lang="en">
      <body>
        <Provider value={{ state, dispatch }}>{children}</Provider>
      </body>
    </html>
  );
}
